
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# default profile
spring:
  application:
    name: apigateway-service
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes: # ??? ??
        - id: first-service # ???? ?? id??? ??? ???? ??
          predicates: # ??
            - Path=/first/** # first-service/ ?? ??? ????
          uri: lb://first # ??? ???? MY-FIRST-SERVICE? ??? ???? ??? ???.
          filters:
            # url ???
            # ?<???>? ?? ??? ???? ???? ??? ? ??? ??. ()? ??? ?? ?? -> segment? (.*)? ??
            # ??(,)? ???? ?? url? ??? url? ?????.
            # ?? ?? ??? ??? ${???}?? url ???? ?? / ?????? ?? ??.
            - RewritePath=/first/(?<segment>.*), /$\{segment}
        - id: second-service
          predicates:
            - Path=/second/**
          uri: lb://release
          filters:
            - RewritePath=/second/(?<segment>.*), /$\{segment}